pub const Format = enum {
    r,
    i,
    s,
    b,
    u,
    j,
    csr,
    compressed,
    vector,
    scalar_other,
};

pub const Semantic = enum {
    raw,
    none,
    rd,
    rd_n0,
    rs1,
    rd_rs1,
    rd_rs2,
    rd_rs1_rs2,
    rd_rs1_imm,
    rd_even_rs1_imm,
    rd_rs1_shamt,
    rd_rs1_csr,
    rd_zimm_csr,
    rd_csr,
    rs1_csr,
    zimm_csr,
    rd_zimm,
    rd_rs1_rm,
    rd_rs1_rs2_rm,
    rd_rs1_rs2_rs3_rm,
    rd_rs1_rs2_bs,
    rd_rs1_rnum,
    rd_rs1_uimm,
    rd_uimm,
    rd_rs1_rl,
    rs1_rs2_aq,
    rs2_imm_rs1,
    rs1_rs2,
    rs1_rs2_offset,
    rs1_offset,
    rs2_rs1_offset,
    rs2_offset,
    rs1_imm5_offset,
    rd_imm20,
    imm20,
    rd_offset,
    offset,
    fence,
    amo,
    lr,
    sc,
    vd_vs2_vs1_vm,
    vd_vs2_rs1_vm,
    vd_vs2_vm,
    vd_rs1,
    vd_vs2_vs1,
    vd_vs2,
    vd_vs2_simm5_vm,
    vd_vs2_zimm5_vm,
    vd_vs2_simm5,
    vd_vs2_zimm5,
    rd_vs2_vm,
    rd_vs2,
    rd_rs1_zimm11,
    rd_zimm5_zimm10,
    vd_vm,
    vd_vs1,
    vd_simm5,
    vd_rs1_nf_vm,
    vs3_rs1_nf_vm,
    vd_rs1_vs2_nf_vm,
    vs3_rs1_vs2_nf_vm,
    vd_rs1_rs2_nf_vm,
    vs3_rs1_rs2_nf_vm,
    vs3_rs1,
    vd_vs2_rs1,
    vd_vs2_zimm6_vm,
    c_none,
    c_mop_t,
    c_rs1,
    c_rd,
    c_rd_rs2,
    c_rd_p_rs2_p,
    c_rd_imm6,
    c_imm6,
    c_rd_uimm6,
    c_rd_p_rs1_p_uimm,
    c_rs1_p_rs2_p_uimm,
    c_rd_sp_uimm,
    c_rs2_sp_uimm,
    c_offset,
    c_rs1_p_offset,
    c_addi16sp,
    c_rd_lui_imm,
    c_addi4spn,
    c_rlist_spimm,
    c_sreg_sreg,
    c_index,
    p_rd_p_rs1_p_rs2_p,
    p_rd_p_rs1_rs2,
    rd_p_rs1_p_rs2,
    p_rd_p_rs1_p_rs2,
    p_rd_p_rs1_p_uimm,
    rd_p_rs1_p_uimm,
    p_rd_p_rs1_p,
    p_rd_p_rs1_uimm,
    p_rd_p_uimm,
    rs1_prefetch_offset,
    mop_r_n,
    mop_rr_n,
    rd_pair_rs1_imm,
};

pub const FieldSpec = struct {
    name: []const u8,
    lsb: u5,
    width: u6,
};

pub const InstructionSpec = struct {
    name: []const u8,
    source_name: []const u8,
    source_file: []const u8,
    match: u32,
    mask: u32,
    format: Format,
    semantic: Semantic,
    bit_width: u8,
    min_xlen: u8,
    max_xlen: u8,
    fields: []const FieldSpec,
};

pub const Operand = union(enum) {
    reg: u5,
    imm: i64,
};

pub const EncodeRequest = struct {
    mnemonic: []const u8,
    xlen: u8,
    operands: []const Operand,
};

pub const EncodedInstruction = struct {
    word: u32,
    bytes: [4]u8,
    len: u8,

    pub fn asSlice(self: *const EncodedInstruction) []const u8 {
        return self.bytes[0..self.len];
    }
};

pub const EncodeError = error{
    ImmediateAlignment,
    ImmediateOutOfRange,
    InvalidXLen,
    MnemonicTooLong,
    OperandCountMismatch,
    OperandKindMismatch,
    RegisterOutOfRange,
    UnsupportedInstruction,
    UnsupportedInstructionWidth,
    UnsupportedXLen,
};
